services:
  - type: web
    name: your-app-name
    env: ruby
    buildCommand: "./bin/render-build.sh"
    startCommand: "bundle exec puma -C config/puma.rb"
    envVars:
      - key: DATABASE_URL
        value: sqlite3:db/production.sqlite3
      - key: RAILS_MASTER_KEY
        sync: false
      - key: RAILS_ENV
        value: production
